<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\RON_VO_VOR_256x256.ico</ApplicationIcon>
	<Version>1.1.1</Version>
	<Company>terryzzz</Company>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\RON_VO_VOR_256x256.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FFMpegCore" Version="5.2.0" />
    <PackageReference Include="NLog" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\RON_VO_VOR_256x256.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Audio\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Tools\UnrealPak\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="VanillaVoiceLists\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
